// Generated by scripts/freeze_catalog.py. Retain all published versions.
import catalog0 from '../../data/catalog-v1.json';
import type { Catalog } from './types';
export const publishedCatalogs = [catalog0] as Catalog[];
