"""Lock a validated version and generate its static browser import registry."""
from datetime import datetime,timezone
import hashlib
import json
from build_data import ROOT,load
from validate_data import validate

validate()
config=load(ROOT/'data/build-config.json')
lock=ROOT/'data/catalog-lock.json'
entries=load(lock) if lock.exists() else []
content=(ROOT/config['file']).read_bytes()
entry={k:config[k] for k in ['version','effectiveFrom','file']}
entry['sha256']=hashlib.sha256(content).hexdigest()
same=next((c for c in entries if c['version']==entry['version']),None)
if same:
    assert same==entry,'Published versions are immutable'
else:
    if entries:
        assert entry['effectiveFrom']>datetime.now(timezone.utc).date().isoformat(),'New versions activate on a future UTC date'
        assert entry['effectiveFrom']>max(c['effectiveFrom'] for c in entries),'Activation must follow existing versions'
    entries.append(entry)
entries.sort(key=lambda c:c['effectiveFrom'])
lock.write_text(json.dumps(entries,indent=2)+'\n')
imports=[f"import catalog{i} from '../../{c['file']}';" for i,c in enumerate(entries)]
source="// Generated by scripts/freeze_catalog.py. Retain all published versions.\n"+'\n'.join(imports)+"\nimport type { Catalog } from './types';\nexport const publishedCatalogs = ["+','.join(f'catalog{i}' for i in range(len(entries)))+"] as Catalog[];\n"
(ROOT/'src/game/catalog-manifest.ts').write_text(source)
print('Frozen catalog '+entry['version']+'; browser registry updated.')
